### PR TITLE
Add tests for non-numerical traits (fix #41)

### LINKED ISSUE #41: Errors when using non-quantitative traits in fd_fric()
We should probably test the behavior of all functions when using non-quantitative traits to make the functions warn the user and not silently compute actual things.

See for example:

``` r
data("aviurba", package = "ade4")
fundiversity::fd_fric(aviurba$traits)
#> Warning in storage.mode(p) <- "double": NAs introduits lors de la conversion
#> automatique
#> Error in geometry::convhulln(traits, "FA"): The first argument should not contain any NAs
```

<sup>Created on 2021-08-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### PR DESCRIPTION
**Pull request by Rekyt**
This PR aims to fix #41 by testing explicitly the behavior of the diversity functions with non-numerical trait data.

It also implements corresponding errors for non-numerical traits.

### CODE REVIEW

**Comment by Rekyt** [comment]
I'm not happy with the code readability of https://github.com/Bisaloo/fundiversity/pull/50/commits/608c2745b3ea755cf086536a1ffa67e90bbc80b1#diff-0c20efce1dedbedf4ae2eaa2e522ec472cdf0d00ca48be1ed56ecf789b3bf898R31-R36

but couldn't think of something better when we have to test that all columns of input traits are numerical.

**Comment by Bisaloo** [comment]
What about doing the test after we convert the df to a matrix. I know it's good to test inputs early but in this specific case, the conversion to a matrix is not super power-intensive so I don't think it's a huge issue.

**Comment by Bisaloo** [comment]
As far as I can tell, if there is a non-numeric column, the resulting matrix will be a `character` object so there shouldn't be any risk of silent errors.

**Comment by Rekyt** [comment]
Indeed, much simpler now!

**Review by Bisaloo — APPROVED** [review]
LGTM.

For what it's worth, I would probably define `traits_birds_cat` next to the test that is using it so we don't have to scroll up to remember its contents but I don't have super strong feelings on this.

**Comment by Bisaloo** [comment]
Oh sorry, forgot about this. Could you also add a bullet for this in the release notes, please?

**Pull request merged**
